ReachFive/identity-android-sdk

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
The `testSuccessfulSignupWithLocalPhoneNumber` test needed that we set the account's country to _France_.
=> Don't ignore the test `testSuccessfulSignupWithLocalPhoneNumber`

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
I have renamed the `open_id` scope into `openid` in the error messages.
=> Rename the `open_id` scope into `openid`

sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthCodeRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
**Asana task**: https://app.asana.com/0/1111569008372652/871746397519508
Initially, the WebViewProvider called the implicit authentication flow. I've replaced it by the authentication flow with code since it's more secure for a mobile application.
To test it, remove the native SDK providers (Facebook & Google) in the client's initialization (in the `MainActivity.kt` file):
```
val providersCreators = listOf(WebViewProvider())
```
and run the application. Click on the _facebook_ button. You'll be asked to enter your Facebook credentials and to accept the consents. In the end, you'll receive an access token.
=> Implement the authentication flow with code in the WebViewProvider

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthCodeRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Pkce.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
**Asana ticket**: https://app.asana.com/0/1111569008372652/871746397519508
I've implemented the PKCE within the authorization code flow called when a user logs in with the `WebViewProvider`.
The PKCE is generated when the user clicks on the login button (in the example, one must click on the provider's name). It's then saved in the [`Intent`](https://developer.android.com/reference/android/content/Intent.html) object and is retrieved in the activity to build the authorize and access token API calls.
=> Call the authorization code flow with PKCE

CHANGELOG.md, build.gradle
- Bump the version to `4.2.0`.
=> Release v4.2.0

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
I've removed the `accessToken` argument from the `requestPasswordReset` method since a user doesn't need to be logged in to request a password reset.
=> Don't pass the `accessToken` in the `requestPasswordReset` method

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/OpenIdUser.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProviderConfig.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1132240385044223
- I have renamed the `User` data class into `OpenIdUser` to be ISO with the iOS SDK. **THIS IS A BREAKING CHANGE!**
- The `idToken` field is now optional in the `AuthToken` data class since login and signup can succeed without it. It must be the SDK developer who fully manages the scopes. 
- I've deleted the tests which check that an error is thrown when the `idToken` is not returned. 
- The `openid` scope is no longer provided by default to the `loginWithProvider` method through the `WebViewProvider`.
=> IdToken is now optional

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1132240385044223
I've added a test to see what's the `getProfile` method response when the `profile` scope is not provided.
=> Add a test for get profile with missing scope

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
Issue #39 
**Fixes**:
- The `authToken` argument of the `updatePassword` method is now optional since it's not required for all the password update use cases.
- I've renamed the `updatePhoneNumberRequest` argument to `updatePasswordRequest`.
=> Delete the `authToken` argument from the `updatePassword`

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt
The parameters `email` and `password` were reversed in the secondary constructor of the `ProfileSignupRequest` model.
=> Fix the signup of the sandbox

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
I've removed the `code` parameter from the `AuthToken` and `AuthTokenResponse` models since it's useless.
=> Delete the `code` parameter from `AuthToken` and `AuthTokenResponse`

app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
I've removed the `redirectUrl` argument from the `logout` method since it's useless for mobile.
=> Delete the `redirectUrl` argument from the `logout` method

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Consent.kt
Issue #46 
The type of the `Consent.consentType` should be a `String` and not a `Boolean`.
=> Change the type of `consentType`

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
* use `authToken: AuthToken` instead of `refreshToken: String` in `refreshAccessToken`
* add `refreshAccessToken` to `JavaReachFive`
=> Refresh Token minor improvements

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
Issue: #53 
- I've added the `errorId` and the `errorUserMsg` attributes to the `ReachFiveApiError` model.
- I've added the `code` attribute to the `ReachFiveError` model.
- The `message` of the `ReachFiveError` model is no longer `Bad Request` or `Technical Error`. It's now equal to the `error` attribute of the `ReachFiveApiError`.
=> Improve the ReachFiveError model

CHANGELOG.md, build.gradle
- Bump the version to `5.3.1`.
=> Release v5.3.1

app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
In the previous version, the redirectUri was an argument of the startPasswordless method.
=> Make redirectUri configurable for passwordless

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Issue #48 
I've specified all the profile's fields in the `getProfile` endpoint URL, otherwise, the custom fields are not returned.
=> Return the custom fields when the profile is fetched

CHANGELOG.md, build.gradle
- Bump the version to `5.4.2`.
=> Release v5.4.2

CHANGELOG.md, build.gradle
- Bump the version to `v5.4.4`.
=> Release v5.4.4

app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/values/settings.xml, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
The **Webview** redirection request code and the **Custom tab** redirection requests code were the same, so the Facebook login was not working anymore (the exchange of the auth code with the access token was never made).
=> Fix the Webview login

CHANGELOG.md
After some tests, I've realized that the integrator doesn't need to specify the client ID in the `AndroidManifest.xml` since this change is only required for Webauthn and not the Webview login.
=> Update the changelog of 6.0.0

README.md
The ReachFive origin domain used for Webauthn will be documented in the ReachFive Slite project.
=> Don't specify the ReachFive origin domain in the README

sdk-core/src/main/AndroidManifest.xml
The Webauth flow wasn't working on some devices: the `RedirectionActivity` activity was recreated so the `code` couldn't be parsed by the `onNewIntent` method. I've updated the `launchmode` of the activity to `singleTask` so that the activity is not recreated if it already exists.
=> Change the launch mode of the `RedirectionActivity` activity

sdk-core/build.gradle, sdk-core/proguard-rules.pro
**Scenario:**
SDK used in an App which uses ProGuard/R8 for obfuscation in a Release build.
**Expected:** 
Everything should work as in a Debug build.
**Actual:**
App crashes due to an NPE on `clientConfig` which is not correctly parsed by the SDK because the JSON/dataClass mapping fails because network model data classes were obfuscated by ProGuard.
[Here the link to where the NPE happens
](https://github.com/ReachFive/identity-android-sdk/blob/9ac15e09e779902ba8682fd75692c9c83e2d6a32/sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt#L59)
**PR explanation:**
This PR adds a rule to avoid network model classes be obfuscated by ProGuard to achieve the expected scenario.
=> Add ProGuard rules for network model classes

CHANGELOG.md
This release contains no actual changes aside from a revised publication target for SDK artifacts which are now uploaded to Sonatype instead of Bintray. The SDK can therefore now be resolved via Maven Central, albeit under a new FQDN: `co.reachfive`. 
⚠️  To prevent breaking changes, this release does not yet change package names. A future release will update package names to `co.reachfive`, which will require you to update your project accordingly!
=> Release v6.2.1

sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
With the exception of `loginWithProvider`, by default, all login methods use the identity client's configured scope. This PR aligns `loginWithProvider`'s behavior with the others.
=> [CA-1221] Use configured identity client scope as default value in SLO flows

build.gradle, libversion.gradle, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/SdkInfos.kt
Fetch the SDK version from the build rather than use a hardcoded string.
=> Get SDK version from a single source

sdk-core/src/main/java/co/reachfive/identity/sdk/core/SessionUtils.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/ErrorCode.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/ReachFiveError.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/SdkInfos.kt
We don't have complete visibility over how this method is used by integrators (i.e., custom implementations). To prevent blocking such potential integrations, reinstate the deprecated method `exchangeCodeForToken`.
=> Reinstate deprecated method

sdk-core/src/main/java/co/reachfive/identity/sdk/core/RedirectionActivity.kt
Since the end of last month, Google declined our app on the Play Store as it's _vulnerable to Intent Redirection_ with the method `co.reachfive.identity.sdk.core.RedirectionActivity.onNewIntent`.
This PR try to prevent the vulnerability another way than it's done today as the upgrade to the `8.1.1` version didn't change anything in Google's warnings about this vulnerability.
As specified in [Google documentation](https://support.google.com/faqs/answer/9267555), we should _Ensure that the extracted Intent is from a trustworthy source_. In this PR, we check if the originating Activity is from trusted package, getting it from the `applicationContext`, matching the **Option 2** of 3 from the above link.
=> fix(intent_redirect): secure intent redirect with expected package name

libversion.gradle, sdk-core/src/main/java/co/reachfive/identity/sdk/core/RedirectionActivity.kt
#173 seems to not have resolved the intent redirection vulnerability warning for some customers. This PR adds simple refactors on top of #175 which implements option 2 of Google's [mitigation document](https://support.google.com/faqs/answer/9267555).
=> [CA-2691] Fix intent vulnerability

libversion.gradle, sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/SignupResponse.kt
https://reach5.atlassian.net/browse/CA-5313
=> [CA-5313] Change return type during signup when identifier is not verified and option forbidUnverifiedIdentifierLoginAfterSignup is enabled

sdk-core/src/main/java/co/reachfive/identity/sdk/core/MfaClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/MfaCredentialsRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/VerifyMfaEmailRequest.kt
[Jira ticket](https://reach5.atlassian.net/browse/CA-4557)
The flag is optional on the backend and defaults to `false`. I opted to always send it and use the same default value if unspecified.
=> Add `trust_device` parameter
