README.md, app/build.gradle, app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/LoginRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SignupRequest.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1126645422034483
- Update the signatures of the `signup` and `loginWithPassword` methods to allow a phone number as an identifier and to provide scopes.
- Create a new method to update a profile.
- Implement integration tests for client initialization, signup, log in with password and profile update.
- Update the typography of the `README.md` file.
=> Implement signup/login with a phone number and profile update

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestPasswordResetRequest.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1126645422034483
I've implemented the method `requestResetPassword` (dev, Java and tests).
=> Implement request password reset

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/VerifyPhoneNumberRequest.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1126645422034483
I've implemented the method to verify a phone number.
=> Implement verify phone number

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
**Asana ticket**: https://app.asana.com/0/1111569008372652/1126645422034483
I've implemented the `updatePhoneNumber` method.
=> Implement update phone number

CHANGELOG.md, README.md, RELEASE.md
I've updated the following files:
- `README.md` 
- `CHANGELOG.md` 
- `RELEASE.md`
=> Update the documentation

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Callback.kt, sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt, sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
**Asana task**: https://app.asana.com/0/1111569008372652/871746397519508
=> Implement password update

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt
**Asana task**: https://app.asana.com/0/1111569008372652/871746397519508
I've renamed the data classed of the `sealed class UpdatePasswordRequest`.
=> Rename the `UpdatePasswordRequest` data classes

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
**Asana ticket**: https://app.asana.com/0/1111569008372652/871746397519508
I've implemented the `logout` method.
=> Implement logout

CHANGELOG.md, build.gradle
- Changelog updated.
- Version bumped to `4.1.0`.
=> Release v4.1.0

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/User.kt
I've translated some Frech comments in English.
=> Translate French comments in English

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
* New random generated Profile per test
* Uniformized fixture creation
=> Improve test fixtures

sdk-core/build.gradle, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
I've added an HTTP logging interceptor to log the API routes called by the application in debug mode.
=> Add an HTTP logger for debug mode

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1132240385044223
I've implemented the `getProfile` method.
=> Implement get profile

app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1132240385044223
Delete the `logoutWithProviders` method and logout the providers in the `logout` method.
=> Merge `logout` and `logoutWithProviders`

CHANGELOG.md, build.gradle
- Changelog updated.
- Bump version to `5.0.0`.
=> Release v5.0.0

CHANGELOG.md, build.gradle
- Bump the version of the SDKs to `5.0.1`.
=> Release v5.0.1

CHANGELOG.md, build.gradle
- Update changelog.
- Bump the version to 5.1.0.
=> Release v5.1.0

app/build.gradle, app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkConfig.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/RefreshRequest.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
Asana: https://app.asana.com/0/1128361015731305/1132216572973271
* enable token refresh using `ReachFive.refreshAccessToken`
* some packaging chores
=> Enable refresh_token grant

CHANGELOG.md, build.gradle
- Update changelog.
- Bump the version to 5.2.0.
=> Release v5.2.0

CHANGELOG.md, build.gradle
=> Release v5.3.0

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProfileAddress.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1136892779385475
I have : 
- corrected the serialization of the `ProfileAddress.isDefault` attribute.
- set all the string attributes of the `ProfileAddress` to `null`.
- corrected the type of the `ProfileAddress.addressType` attribute.
- added an integration test for signup with a complete profile address.
=> Fix the profile address model

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1137149519557513
I've just deleted the `signedUid` attribute from the `Profile` model.
=> Remove the `signedUid` attribute from the profile

sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
=> Remove no provider found error

CHANGELOG.md, build.gradle
- Bump the version to `5.3.2`.
=> Release v5.3.2

sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Issue #48 
I've forgotten to add some fields in the get profile request.
=> Add missing fields in the get profile request

CHANGELOG.md, build.gradle
- Bump the version to ` v5.4.3`.
=> Release v5.4.3

build.gradle, gradle/wrapper/gradle-wrapper.properties, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProviderConfig.kt
Removes unused value in providers config.
Gradle auto-updated and so I included that in this PR.
=> Update providers config

.gitignore, README.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkConfig.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/AuthCodeRequest.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
[Asana ticket](https://app.asana.com/0/1108828962586858/1178242432075300/f)
=> Configure scheme with client ID

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/Provider.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt, sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
**Asana task**: https://app.asana.com/0/1111569008372652/1181946424712969
=> Add the `scope`parameter to the `loginWithProvider` method

app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
[[SDK Android] Rajouter les error message key dans les error bodies](https://app.asana.com/0/980131104682803/1160053512301237/f)
=> Add error_message_key in error bodies

app/src/main/AndroidManifest.xml, app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/activity_authenticated.xml
**Asana ticket**: https://app.asana.com/0/1141396442496489/1184670283732693
=> Redirect the user to an authenticated page after a successful login

app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt, app/src/main/java/com/reach5/identity/sdk/demo/DevicesAdapter.kt, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/device_item.xml, app/src/main/res/layout/webauthn.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/DeviceCredential.kt
**Asana task**: https://app.asana.com/0/1141396442496489/1187253145208753
=> List the FIDO2 registered devices

app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt, app/src/main/java/com/reach5/identity/sdk/demo/DevicesAdapter.kt, app/src/main/res/layout/device_item.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
**Asana task**: https://app.asana.com/0/1141396442496489/1187409692541809
=> Delete a FIDO2 registered device

app/build.gradle, app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt, app/src/main/java/com/reach5/identity/sdk/demo/DevicesAdapter.kt, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/activity_authenticated.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/webauthn_devices.xml, app/src/main/res/layout/webauthn_login.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/AuthenticationPublicKeyCredential.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/RegistrationPublicKeyCredential.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebAuthnLoginRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebAuthnRegistrationRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/ReachFiveToken.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/AuthenticationOptions.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/DeviceCredential.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/R5PublicKeyCredentialDescriptor.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/RegistrationOptions.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/RegistrationPublicKeyCredential.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Scope.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/WebAuthn.kt
**Asana task**: https://app.asana.com/0/1141396442496489/1181397055064771
=> Login with a registered FIDO2 device

app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/webauthn_signup.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFiveWebAuthn.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebAuthnRegistrationRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebauthnSignupCredential.kt
**Asana task**: https://app.asana.com/0/1141396442496489/1181397055064779
=> Implement FIDO2 signup

README.md, app/src/main/AndroidManifest.xml, app/src/main/res/values/settings.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/AndroidManifest.xml
Asana task: https://app.asana.com/0/1141396442496489/1181397055064779
=> Fix redirection with any scheme provided

app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
With my latest PR which fixes the Webview Provider login, I broke the Native Provider login :/
=> Fix the native provider login

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/values/settings.xml, sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
Asana task : https://app.asana.com/0/1141396442496489/1181397055064779
fix Redirection scheme Android SDK and update regex of WebViewClient
=> update scheme format

sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
Asana task : https://app.asana.com/0/1198995533452093/1199141296941896
fix webView user-agent
=> fix webView user-agent

app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt, sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/SignupRequest.kt
**Asana ticket**: https://app.asana.com/0/1141396442496489/1199342593301357
=> Add the redirectURL parameter in the signup method

sdk-core/src/main/java/com/reach5/identity/sdk/core/models/OpenIdUser.kt
[Asana](https://app.asana.com/0/1141396442496489/1200035313314228)
=> Add external ID to OpenIdUser

README.md
=> [README] Append note about gradle version

app/build.gradle, sdk-facebook/build.gradle
[Jira](https://reach5.atlassian.net/browse/CA-349?atlOrigin=eyJpIjoiZTIwOTIxMTk2YzQ2NDNhNWI4OGIxNzQ0YmJiNzllMGQiLCJwIjoiaiJ9)
=> [CA-349] Update du SDK Facebook

sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt
=> Use `/userinfo` instead of `/me`

CHANGELOG.md
Note that I (shouldn't have) bumped version in `libversion.gradle` in PR #152.
=> Release v7.0.2

sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/OpenIdUser.kt
https://reach5.atlassian.net/browse/CA-1563
=> Make `Address` fields nullable

libversion.gradle
Minor additions to the recent major release.
=> Release v8.0.1

sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/LoginRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/ProfileSignupRequest.kt
https://reach5.atlassian.net/browse/CA-1781
This PR adds the custom identifier to the payload request for signup and login
=> [CA-1781] Add custom identifier to signup and login

CHANGELOG.md
=> Release v8.1.2

sdk-wechat/src/main/java/co/reachfive/identity/sdk/wechat/WeChatLoginActivity.kt, sdk-wechat/src/main/java/co/reachfive/identity/sdk/wechat/WechatProvider.kt, sdk-wechat/src/main/java/co/reachfive/identity/sdk/wechat/share/WXEntryActivity.kt
https://reach5.atlassian.net/browse/CA-3370
=> [CA-3370] Trigger specific error messages

build.gradle, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/AcceptLanguageInterceptor.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt
[Jira](https://reach5.atlassian.net/browse/CA-3269): Add Accept-Language header in the requests sent to the backend
=> [CA-3269] Take system language into account

sdk-core/src/main/java/co/reachfive/identity/sdk/core/MfaClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/MfaCredentialsRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/ListMfaCredentials.kt
https://reach5.atlassian.net/browse/CA-3411
+  add a specific request for verify phone number mfa request without the phone number
=> [CA-3411] Add list mfa credentials method

sdk-core/src/main/java/co/reachfive/identity/sdk/core/ActivityResultHandler.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordlessClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/SessionUtils.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/WebauthnClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/LoginRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/PasswordlessStartRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/SignupRequest.kt
https://reach5.atlassian.net/browse/CA-3179
=> [CA-3179] Add missing origin param to multiple methods

sdk-core/src/main/java/co/reachfive/identity/sdk/core/MfaClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/MfaCredentialsRequest.kt
https://reach5.atlassian.net/browse/CA-1418
=> [CA-1418] Delete mfa credential

CHANGELOG.md, sdk-core/src/main/java/co/reachfive/identity/sdk/core/MfaClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/TrustedDevicesResponse.kt
https://reach5.atlassian.net/browse/CA-3823
=> [CA-3823] Add get listMfaTrustedDevices + removeMfaTrustedDevice

sdk-core/src/main/java/co/reachfive/identity/sdk/core/MfaClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/MfaCredentialsRequest.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/MfaStepUpRequest.kt
https://reach5.atlassian.net/browse/CA-4880
=> [CA-4880] Add action to step up and mfa registering

sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt, sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/RequestPasswordResetRequest.kt
https://reach5.atlassian.net/browse/CA-5278
=> [CA-5278] Add origin parameter to requestPasswordReset
